default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

# PRODUCCIÓN: Aquí ocurre la magia
production:
  primary: &primary_production
    <<: *default
    adapter: postgresql # Usamos Postgres
    encoding: unicode
    url: <%= ENV['DATABASE_URL'] %> # Render llenará esto solo
    pool: 5
  cache:
    <<: *primary_production # Reusa la conexión de arriba
    database: production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production # Reusa la conexión de arriba
    database: production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production # Reusa la conexión de arriba
    database: production_cable
    migrations_paths: db/cable_migrate
